services:
  koha:
    image: mbledkowski/koha:latest
    volumes:
      - koha_database:/database
    ports:
      - "80:80"
      - "8080:8080"
    cap_add:
      - SYS_NICE
      - DAC_READ_SEARCH
volumes:
  koha_database:
    external: true